// Code generated by go-bindata.
// sources:
// sql/createTables.sql
// DO NOT EDIT!

package exec

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _sqlCreatetablesSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\x8f\xdd\x4a\xc4\x30\x10\x85\xaf\x27\x4f\x31\x97\x0a\xfb\x06\x5e\xd5\x75\x94\xa0\x9b\x4a\x76\x84\xee\x55\x88\x6d\x08\x85\x6d\xb2\xa6\xb6\xec\xe3\x4b\xa5\x4a\x2a\xf5\xef\x6e\x38\x0c\xdf\xf9\xce\x56\x53\xc1\x84\x5c\x5c\x3f\x10\xca\x5b\x54\x25\x23\x55\x72\xcf\x7b\xf4\x29\x0e\xa7\xde\x1c\xa3\xc7\x0b\x01\xc7\xe8\x4d\xef\x5e\x06\x17\x6a\x67\xc2\xd0\x3d\xbb\x04\x52\x31\xdd\x91\x06\x78\xd4\x72\x57\xe8\x03\xde\xd3\x01\x8b\x27\x2e\xa5\xda\x6a\xda\x91\xe2\x8d\x00\x5b\xbf\xb6\x31\x98\x60\x3b\x07\xc0\x54\x4d\x59\x1d\xbb\xce\x86\xc6\xb4\xcd\x67\xf4\xde\x96\x7d\x89\xcb\x2b\x21\x66\x3b\xa9\x6e\xa8\xfa\x62\x37\x63\xdb\xe6\x8c\xa5\x5a\xb8\xae\x98\x6e\x30\xb3\xc8\xc0\x6b\xb3\x67\xb7\x7e\x1a\xbd\xe2\x79\x9a\xee\x8f\xe5\xbf\x78\xff\x80\x37\x36\xf9\xef\x2a\xda\xe6\xbc\xa8\xb0\xc9\xc3\xff\xe0\x2e\x8c\x7f\x64\xbb\x30\x9a\xd1\xa6\x8c\xff\x16\x00\x00\xff\xff\xfb\x26\xb2\x9c\x12\x02\x00\x00")

func sqlCreatetablesSqlBytes() ([]byte, error) {
	return bindataRead(
		_sqlCreatetablesSql,
		"sql/createTables.sql",
	)
}

func sqlCreatetablesSql() (*asset, error) {
	bytes, err := sqlCreatetablesSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "sql/createTables.sql", size: 530, mode: os.FileMode(420), modTime: time.Unix(1492348181, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"sql/createTables.sql": sqlCreatetablesSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"sql": &bintree{nil, map[string]*bintree{
		"createTables.sql": &bintree{sqlCreatetablesSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

